apiVersion: v1
kind: Service
metadata:
  name: pod-info-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: pod-info
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: explore-california-service
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: explorecalifornia.com
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: development
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path:   /
    prometheus.io/port:   '8080'
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000